name: MineCards
description: $description
version: '${version}'

main: dev.cheech.MineCards
api-version: '26.1.2'
load: POSTWORLD

authors: [ Frank D, Matt B ]

commands:
  givepack:
    description: gives the player a pack