name: MineCards
description: $description
version: '${version}'

main: dev.cheech.MineCards
api-version: '26.1.2'
load: POSTWORLD

authors: [ Frank D, Matt B ]

permissions:
  minepacks.admin:
    description: Allows access to the admin command.
    default: op

commands:
  givepack:
    description: gives the player a pack
    usage: /givepack [player] [packname]
    permission: minepacks.admin
    permission-message: §cYou do not have permission to execute this command!
  givebinder:
    description: gives the player a binder
    usage: /givepack [player]
    permission: minepacks.admin
    permission-message: §cYou do not have permission to execute this command!
  displaypack:
    description: shows the potential contents of a pack to the player
    usage: /givepack [packname]
  reloadpacks:
    description: reloads all the packs
    usage: /reloadpacks
    permission: minepacks.admin
    permission-message: §cYou do not have permission to execute this command!
  updateinv:
    description: updates all cards in inventory to the latest version
    usage: /updateinv